// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAcgL8--sthP0zm9gcTRLgKKDX0ioXd_0M",
    appId: "1:398051540701:web:bf384056f7cef09bc6e534",
    messagingSenderId: "398051540701",
    projectId: "chat-demo-c58d4",
    authDomain: "chat-demo-c58d4.firebaseapp.com",
    databaseURL: 'https://chat-demo-c58d4.firebaseio.com',
    storageBucket: 'chat-demo-c58d4.appspot.com',
    measurementId: "G-04KDZMDXQ9"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDayLtkMTEXQp-zMXjjI2h7YbJ_HiMjDGs',
    appId: '1:398051540701:android:6e4e36a2dee66a23c6e534',
    messagingSenderId: '398051540701',
    projectId: 'chat-demo-c58d4',
    storageBucket: 'chat-demo-c58d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuR4KJ4AW5YTfpBentNpJswzbqzHLHFJo',
    appId: '1:398051540701:ios:739a60f4f188853cc6e534',
    messagingSenderId: '398051540701',
    projectId: 'chat-demo-c58d4',
    storageBucket: 'chat-demo-c58d4.appspot.com',
    iosClientId: '398051540701-pd118dooujdm91lchq7bqn4no5tilgt0.apps.googleusercontent.com',
    iosBundleId: 'com.hyperlink.flutterDemoStructure',
  );
}
